---
dist: xenial
language: minimal
git:
  depth: 5

#

.node_stage: &node_stage
  language: node_js
  node_js: 10
  before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
  cache:
    yarn: true
  install:
    - yarn --frozen-lockfile

#

jobs:
  include:
    - <<: *node_stage
      name: Puppetteer
      before_script:
        - yarn run -- lerna exec --scope=@runner/puppetteer -- yarn --frozen-lockfile
      script:
        - yarn lerna run --scope=@runner/puppetteer test
    - <<: *node_stage
      name: Webdriver
      addons:
        browserstack:
          username: douglas111
          access_key:
            secure: "ERN68dHerSUM5Q975t4A6xyQJI3yI9f0kDlrJlDhieKvFPKU3+6/ui6cqnnK378gsylOW6YHnQiquYAfo2GBMreX+axdmv/oD7kPOxXVSAZ07RckjfLwvMOvbihwiVeNhQ9/Muo/4QlBzLURGd3XMsGWd1bWG4nYtliI3S9RZZrsl6PNifqL2Bc4cTItoBz/m8AKkWGoX7HGmP4rXX4N7J+cMeJwGc3ykejgUMIoLIh3Ei+pUL3IIbkHSROJvMP1tB6iuQ8Jjvyl/zpvM6qJ+bgMCLTyh8R7yPfAfXBRA9HEJPXQjPWWltlr5xcVHHclmMO6qj/YyiwXc1Gd29gDT1XCyV1Ca9qFoJTD3bwaD7WysN4NA1ZYY5h04QB4+/qByYM/gIuOT38wMco+OG3KLJQNuZlkGJr6KORYXEUtaLWcdym3jvZr9aC+p7LePzZl8tQKUYR0fpvlc/NDlQjmx3aA1Qs4dFFnxjPvvYBQT91IZE7nq0ETcaLPV5Xn0ng3rF58Vo7mJwY9vfEoN46BYFPRrWxySzwJrq1kWqNX7wOecpvEbYa7FfArWkKlrrn+ZElWCate1XpQmtkECkqP62qbhe99Nz83jbRatg87dzHVRLYwJLgYZbUpAdAiv/JKsda4iygBhHpvCP0+aQ0NFeZEBkH+L4bFUu+XJy4q3AU="
      env:
        - secure: "R8erQLP8iKwgAdJ4UkPYE3DKhJuOPQHal0CHgC3cIGzhpOOLWwr4QI7qyKBihd1N37Bym/zqF1GemUwe96z9cHLuhLiMPAi2RgubHHv6gWehoHgEPtXGmlFYR04ScRQ6aXQE2E2hKZBbD6501iQomwtu28gJU6WFlg1enyBrLQwCB++iBeZgKrhHL6ldhIvBNgxKb8Rxs0Oy3S7E7wN/uZ60iZHnes9PN9o7d9QXFulINBQ3hwoWsj/v54rWJWv9eS1DVfohqxshETWMo9KRuTLRN4DeMdg15wiBSw8AcKAM/WJ8nQnYcmbiFXpwjEdlG8c82C3XQl2vsctyoMJTy6nxsxUrgcasXTQlMm+mXUd3zsRO89le1STeVhZMl0YghqlQ76UvamlovwKOuOCiI8zN85BJnPGk0DZUSMF/C/jQyM/8s55iKlrFPsHXJ9WXVInMcA0r2NLy2Ihm82N9Q/cXVDxHQgST9Uchl/O4GsPkwtRZkNpFaI+8XjTlcKnI4Nxp5LJ9lN/z/yz+5qZf93653WB/OgSBkf5YTRIRxbSqJmJDUQ8N58QfTpLt3I3X2qnVHxQ6HsbKigH8pfSuN+9hk6ZrzEnj1Duh1mZCOOcvhmMxTLb9Lk6VTG21bxpKSaabgTquKDeNxLlzMF+zUKPZxx8MPJzq4wQ1kpbGCck="
        - secure: "JcSzwtvjA58UCN6Qy53CtCoE8R3JGhVOC3GKSuSWcp6KTr7TJWEdvPvADWbGcpchfyn010xnNrQOihho3K3mXwye9hc6ktNC7Dvxi0mvcGGJFLqdn3WmsTGNBYkdjK7egY62D/MyuMJ0w0Re7/8kd8znztvlynyuWMxjREq3HJpPCqyWZM6o1R055RpblAc4Cz2CVujvNi4a0x3nffKDQxA5LXdnPS7T0LYnPEf6EjlqJ9H0qqt/pgb9ZVFjQ+oqZ6G0vz5oDHJ483GN/mtgnDlLXqOk1WZ4UjQ5LalQ5Rs62Jn37V0JxjheT580bgGPXi1jssn3hGzj4ZHBQtWxKUGm3EjYEV/LB3H4xbIyZPWMK9HKJ1GKJbVKezEgOCyHlWeUcn49C8nJhQcuRQU1qCCDb2GYM98N+AyDNlFCXEiu/PKomgnMi9AcrMuuD7csBlnwoo6JAqN0ossG7gRxc6P0iCI1vDVMD5G/E7JatEd8S55QivJiVaDJiVLv4LNjSMjQDyTGg/sytqJ40gc4kd/hcPr8PlE1+87rPCZMI1VUer1A/Fq0sNz0OgXJMLClALYg2ICmoTkQcsrDESpkrBFT/yWi1M5Jav9L8XoZIyYUerGxSd1eEHNzo+z/JWpmxvqZO09cSqC71PXgOIgcztwKsMOzFBxaMY5VCsqMIjw="

      before_script:
        - yarn run -- lerna exec --scope=@runner/webdriver -- yarn --frozen-lockfile
      script:
        - yarn lerna run --scope=@runner/webdriver test
